---
- name: Validate DB runInstaller exists
  ansible.builtin.stat:
    path: "{{ oracle_home }}/runInstaller"
  register: db_inst
  when: inventory_hostname == (groups['oracle_managed_hosts'] | default([]) | first)

- name: Assert DB software installed
  ansible.builtin.assert:
    that:
      - db_inst.stat.exists
  when: inventory_hostname == (groups['oracle_managed_hosts'] | default([]) | first)
