---
- import_tasks: 00_topology_from_oracle_hosts.yml
- import_tasks: 01_precheck_network.yml
- import_tasks: 02_os_packages.yml
- import_tasks: 03_users_groups.yml
- import_tasks: 04_create_folders.yml
- import_tasks: 05_shared_disks_udev.yml
- import_tasks: 06_grid_software_install.yml
- import_tasks: 07_gridsetup.yml
- import_tasks: 08_grid_rootsh.yml
- import_tasks: 09_executeconfigtools.yml
- import_tasks: 10_grid_postcheck.yml
- import_tasks: 11_db_software_unzip.yml
- import_tasks: 12_db_software_install.yml
- import_tasks: 13_db_rootsh.yml
- import_tasks: 14_db_postcheck.yml
- import_tasks: 15_create_diskgroups.yml
- import_tasks: 16_create_orcl_database.yml
- import_tasks: 17_summary.yml
- import_tasks: 18_change_all_passwords.yml
