---
- name: Undo 18 rollback root/oracle/grid passwords
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: always
  loop:
    - { name: "root", password: "{{ root_user_password_old }}" }
    - { name: "{{ oracle_user }}", password: "{{ oracle_user_password_old }}" }
    - { name: "{{ grid_user }}", password: "{{ grid_user_password_old }}" }
  failed_when: false

